"""Added table Users

Revision ID: 35f884a83456
Revises: 
Create Date: 2023-11-27 22:06:31.806868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f884a83456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID to telegram', sa.Integer(), nullable=False),
    sa.Column('First name', sa.String(length=50), nullable=True),
    sa.Column('Second name', sa.String(length=50), nullable=True),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Phone number', sa.String(length=18), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ID to telegram')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
