name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upgrade pip and wheel
        run: python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run pylint tests
        run: python -m pip install --upgrade pip && pip install pylint
      - name: Lint
        run: pylint --rcfile=.pylintrc $(git ls-files '*.py')
